public class ContactDataWrapper {
    public Contact con		{get;set;}
    public Integer age		{get;set;}
    public String  email	{get;set;}
	
    // We can initialize/assign memory here
    // or
    // We can initialize/assign memory where we are using the Object.
    
    // Fields used in List_Of_List_Examples
    
    public String FirstName;
    public String LastName;
    public Integer PersonAge;
    public Decimal Salary;
    
    
}